## Summary stats ----

# generates a summary of a grouped dataframe with x column for data for discrete
# counts.
# df_shape = diamonds %>% dplyr::group_by(cut) %>% .get_shape(cols = dplyr::vars(color))
# grp_df = df_shape$.source[[1]]
# .subtype_count(grp_df)
.subtype_count = function(grp_df) {
  if (is.logical(grp_df$x)) grp_df = grp_df %>% dplyr::mutate(x = factor(ifelse(x,"true","false")))
  if (is.numeric(grp_df$x)) grp_df = grp_df %>% dplyr::mutate(x = factor(as.character(x)))
  grp_df %>% dplyr::group_modify(function(d,g,...) {
    col = d$x
    tibble::enframe(table(col),name = "level",value = "n") %>%
      dplyr::mutate(level = factor(level, levels=levels(grp_df$x)), x = as.integer(n), n = sum(n)) %>%
      dplyr::mutate(binom::binom.confint(x=x, n=n, methods="wilson")) %>%
      dplyr::rename(prob.0.5=mean, prob.0.025=lower, prob.0.975=upper) %>%
      dplyr::mutate(
        .order2 = dplyr::row_number(),
        N = length(col)
      ) %>%
      dplyr::select(-method)
  })
}

# generates a summary of a grouped dataframe with x column for data for
# non normal continuous data
# grp_df = iris %>% dplyr::group_by(Species) %>% dplyr::select(x = Petal.Width)
# .median_iqr(grp_df)
.median_iqr = function(grp_df) {
  quantiles = c(0.025,0.05,0.25,0.5,0.75,0.95,0.975)
  grp_df %>% dplyr::group_modify(function(d,g,...) {
    col = d$x
    tibble::as_tibble_row(
      stats::quantile(col, quantiles, na.rm=TRUE) %>% magrittr::set_names(sprintf("q.%1g", quantiles))
    ) %>% dplyr::mutate(
      n = length(stats::na.omit(col)),
      N = length(col),
      .order2 = 1
    )
  })
}

# generates a summary of a grouped dataframe with x column for data for
# normal continuous data
# grp_df = iris %>% dplyr::group_by(Species) %>% dplyr::select(x = Petal.Width)
# .mean_sd(grp_df)
.mean_sd = function(grp_df) {
  grp_df %>% dplyr::summarise(
    mean = mean(x, na.rm = TRUE),
    sd = stats::sd(x, na.rm = TRUE),
    n = length(stats::na.omit(x)),
    N = length(x),
    .order2 = 1,
    .groups = "keep"
  )
}

# generates a summary of a grouped dataframe with x column for data for
# none of the above.
# grp_df = iris %>% dplyr::group_by(Species) %>% dplyr::select(x = Petal.Width)
# .skipped(grp_df)
.skipped = function(grp_df) {
  grp_df %>% dplyr::summarise(
    n = length(stats::na.omit(x)),
    N = length(x),
    .order2 = 1,
    .groups = "keep"
  )
}

.summary_types= list(
  "subtype_count" = .subtype_count,
  "median_iqr" = .median_iqr,
  "mean_sd" = .mean_sd,
  "skipped" = .skipped
)

# generate summary stats for each of the columns of a dataframe, depending on
# the nature of that column (and determined by .get_shape).
# df_shape is as generated by .get_shape()
# df_shape = diamonds %>%  dplyr::mutate(is_clear = ifelse(clarity>"VS2","clear","less clear")) %>% dplyr::group_by(is_clear) %>% .get_shape()
# df_shape %>% .summary_stats()
# df_shape = iris %>% dplyr::group_by(Species) %>% .get_shape()
# df_shape %>% .summary_stats()
.summary_stats = function(df_shape, override_type = list() ) {

  override_type = as.list(override_type)

  # See if user wants to override summary type?
  if (length(override_type) > 0) {
    if (any(!override_type %in% names(.summary_types)))
      stop("override types must be one of ", paste0(names(.summary_types),collapse=", "))
    # override_type = list("multinom_class"="mean_sd")
    override = tibble::tibble(
      .name = names(override_type),
      .override_type = unname(unlist(override_type))
    )
    df_shape = df_shape %>% dplyr::left_join(override, by=".name") %>%
      dplyr::mutate(.summary_type = ifelse(!is.na(.override_type), .override_type, .summary_type)) %>%
      dplyr::select(-.override_type)
  }

  df_shape$.summary_data = list(rep(NA,nrow(df_shape)))
  for (i in 1:nrow(df_shape)) {
    # get dataframe row as a list
    tmp = df_shape %>% purrr::map(~ .x[[i]])
    .message(tmp$.summary_type, " summary for ",tmp$.label)
    fun = .summary_types[[tmp$.summary_type]]
    d = tmp$.source
    result = fun(d)
    df_shape$.summary_data[[i]] = result
  }

  df_shape = df_shape %>% dplyr::mutate(
      N_total = sapply(.content, length),
      N_present = sapply(.content, function(x) length(stats::na.omit(x)))
    )

  return(structure(
    df_shape,
    class = c("t1_summary",class(df_shape))))
}

